import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Library Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.ico" sizes="any" />

          <link rel="stylesheet" href="/Keyboard/css.css" />
          <script src="/Keyboard/keyboard.js"></script>
          <title>Virtual-Keyboard</title>
      </head>
      <body className={inter.className}>{children}
      
        <script src="initialize.js"></script> 
      </body>
    </html>
  );
}
